version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_ALCHEMY_API_KEY
        - NEXT_PUBLIC_ALCHEMY_POLICY_ID
        - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
        - NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_CONTRACT_ADDRESS
        - NEXT_PUBLIC_RPC_URL
        - NEXT_PUBLIC_ENABLE_TESTNETS
        - NEXT_PUBLIC_GA_ID
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - HOST=0.0.0.0
    env_file:
      - env.production
    depends_on:
      - mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      aristhrottle-network:
        aliases:
          - api
          - app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aristhrottle
      - MONGO_INITDB_ROOT_PASSWORD=3f484sVzFrDthL9o
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - aristhrottle-network

volumes:
  mongodb-data:

networks:
  aristhrottle-network:
    driver: bridge 