export const data = [
  { votes: 2 },
  { votes: 1 },
  { votes: 9 },
  { votes: 19 },
  { votes: 18 },
  { votes: 18 },
  { votes: 13 },
  { votes: 12 },
  { votes: 1 },
  { votes: 12 },
  { votes: 13 },
  { votes: 19 },
  { votes: 14 },
  { votes: 7 },
  { votes: 3 },
  { votes: 0 },
  { votes: 20 },
  { votes: 9 },
  { votes: 17 },
  { votes: 20 },
  { votes: 0 },
  { votes: 0 },
  { votes: 13 },
  { votes: 17 },
  { votes: 14 },
]
