import type { Metadata } from 'next'
import localFont from 'next/font/local'
import WalletProvider from '@/config/walletProvider'
import '@rainbow-me/rainbowkit/styles.css'
import ChakraUIProvider from '@/config/chakraProvider'
import { ToastContainer } from 'react-toastify'
import ContextProvider from '@/context/contextProvider'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'
import Starfield from '@/components/Starfield'
// import CursorAristhrottle from "@/components/CursorAristhrottle";

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Aristhrottle',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark'>
      <head>
        <style>
          @import
          url(&apos;https://fonts.googleapis.com/css2?family=Jersey+10&display=swap&apos;);
        </style>
        
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Starfield
          starCount={2000}
          starColor={[255, 255, 255]}
          speedFactor={0.05}
          gradientTopColor='#000000'
          gradientMidColor='#000000'
          gradientBottomColor='#1b1f3b'
        />
        <ContextProvider>
          <ChakraUIProvider>
            <WalletProvider>{children}</WalletProvider>
          </ChakraUIProvider>
          <ToastContainer theme='dark' />
        </ContextProvider>
        {/* <CursorAristhrottle /> */}
      </body>
    </html>
  )
}
