
import type { Metadata } from "next";
import localFont from "next/font/local";
import WalletProvider from "@/config/walletProvider";
import ChakraUIProvider from "@/config/chakraProvider";
import { ToastContainer } from "react-toastify";
import ContextProvider from "@/context/contextProvider";
import "@rainbow-me/rainbowkit/styles.css";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Aristhrottle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          {" "}
          @import
          url(&apos;https://fonts.googleapis.com/css2?family=Jersey+10&display=swap&apos;);
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <ContextProvider>
            <ChakraUIProvider>
              <WalletProvider>{children}</WalletProvider>
            </ChakraUIProvider>
            <ToastContainer theme="dark" />
          </ContextProvider>
      </body>
    </html>
  );
}
